name: Build and Deploy

on:
  push:
    branches: 
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps :
      
      - name: Install lowdown
        run: |
          git clone https://github.com/kristapsdz/lowdown.git
          cd lowdown
          ./configure
          make
          sudo make install
          cd ..
      
      - name: Install romanzolotarev/ssg5
        run: |
          mkdir -p bin
          cd bin
          curl -L https://www.romanzolotarev.com/bin/ssg5 > ssg5
          chmod +x ssg5
          cd ..
         
